Doxygen: UI Class Reference
UI Class Reference
#include <UI.h>
Public Member Functions
UI ()
std::string startMenu ()
bool continuePrompt ()
int continueProgram (std::string)
std::string enterFileName ()
void printMetadata (const FileManager &)
std::string processorMenu ()
bool continueProcessor (std::string)
std::vector< int > echoOptions (const FileManager &)
int gainOption (const FileManager &)
void exitScreen ()
void printError ()
void printError (const std::string &, int=2)
void printError (const std::ostringstream &, int=2)
void println (const std::string &)
void delay (double)
void clearConsole ()
Private Member Functions
int promptProcessor (const std::string &, const std::string &)
int promptGain (const std::string &)
Detailed Description
Definition at line 12 of file UI.h.
Constructor & Destructor Documentation
UI()
UI::UI ()
Definition at line 4 of file UI.cpp.
        {
     clearConsole();
     println("Welcome to the start menu");
 }
References clearConsole(), and println().
Member Function Documentation
clearConsole()
void UI::clearConsole ()
Definition at line 164 of file UI.cpp.
                       {
     std::system("clear");
 }
Referenced by echoOptions(), enterFileName(), exitScreen(), gainOption(), printError(), printMetadata(), and UI().
continueProcessor()
bool UI::continueProcessor (std::string userInput)
Definition at line 64 of file UI.cpp.
{
     return (userInput.length() == 1 && userInput.find_first_not_of("0123") == std::string::npos);
 }
Referenced by main().
continueProgram()
int UI::continueProgram (std::string userInput)
Definition at line 16 of file UI.cpp.
{
     if (userInput == "N" || userInput == "n") {
         return 0;
     } else if (userInput == "Y" || userInput == "y") {
         return 1;
     } else {
         return 2;
     }
 }
Referenced by main().
continuePrompt()
bool UI::continuePrompt ()
delay()
void UI::delay (double dseconds)
Definition at line 160 of file UI.cpp.
{
     int iseconds = static_cast<int>(dseconds * 1000);
     std::this_thread::sleep_until(std::chrono::system_clock::now() + std::chrono::milliseconds(iseconds));
 }
Referenced by exitScreen(), printError(), and printMetadata().
echoOptions()
std::vector< int > UI::echoOptions (const FileManager & file)
Definition at line 68 of file UI.cpp.
{
     clearConsole();
     std::vector<int> options;
     std::string promptDelay = "How long would you like the delay between echoes to be in seconds?";
     bool isValid = false;
     double timeDelay;
     do {
         timeDelay = promptProcessor(promptDelay, "Delay Time: ");
         if (timeDelay > file.getFileDuration()) {
             std::ostringstream error;
             error << "ERROR: Echo delay should be shorter than " << file.getFileDuration() << " seconds (the duration of the WAV file).";
             printError(error, 5);
         } else {
             isValid = true;
         }
     } while (!isValid);
     options.push_back(timeDelay);
     clearConsole();
     std::string promptDecay = "What loudness percentage of the original audio do you want the echo to be (0 - 100)?";
     isValid = false;
     int decay;
     do {
         decay = promptProcessor(promptDecay, "Decay Factor: ");
         if (decay < 0 || decay > 100) {
             printError("ERROR: Please enter a number between 0 and 100.", 4);
         } else {
             isValid = true;
         }
     } while (!isValid);
     options.push_back(decay);
     return options;
 }
References clearConsole(), FileManager::getFileDuration(), printError(), and promptProcessor().
Referenced by main().
enterFileName()
std::string UI::enterFileName ()
Definition at line 26 of file UI.cpp.
{
     clearConsole();
     std::cout << "Enter the name of the WAV file you would like to process:\n";
     std::string fileInput;
     std::cin >> fileInput;
     if (fileInput.find(".wav") == std::string::npos) {
         if (fileInput.find(".wave") == std::string::npos) {
             fileInput += ".wav";
         }
     }
     return fileInput;
 }
References clearConsole().
Referenced by main().
exitScreen()
void UI::exitScreen ()
Definition at line 134 of file UI.cpp.
                     {
     clearConsole();
     std::cout << "Closing application";
     delay(2);
     //clearConsole();
 }
References clearConsole(), and delay().
Referenced by main().
gainOption()
int UI::gainOption (const FileManager &)
Definition at line 118 of file UI.cpp.
{
     clearConsole();
     std::string promptScale = "By what percentage do you want to scale your audio (0 - 100)?";
     int gain;
     bool isValid = false;
     do {
         gain = promptProcessor(promptScale, "Gain Adjustment: ");
         if (false) { //if (gain > newProcessor.maxScalabilty)
             printError("WARNING: Audio data will be compressed and may sound distorted.", 4);
         } else {
             isValid = true;
         }
     } while (isValid);
     return gain;
 }
References clearConsole(), printError(), and promptProcessor().
printError() [1/3]
void UI::printError ()
Definition at line 141 of file UI.cpp.
                     {
     println("ERROR: Invalid input. Please try again.");
     delay(2);
     clearConsole();
 }
References clearConsole(), delay(), and println().
Referenced by echoOptions(), gainOption(), main(), and promptProcessor().
printError() [2/3]
void UI::printError (const std::ostringstream & error, int time = 2)
Definition at line 151 of file UI.cpp.
{
     std::cout << error.str() << "\n";
     delay(time);
     clearConsole();
 }
References clearConsole(), and delay().
printError() [3/3]
void UI::printError (const std::string & error, int time = 2)
Definition at line 146 of file UI.cpp.
{
     std::cout << error << "\n";
     delay(time);
     clearConsole();
 }
References clearConsole(), and delay().
println()
void UI::println (const std::string & line)
Definition at line 157 of file UI.cpp.
{
     std::cout << line << "\n";
 }
Referenced by printError(), printMetadata(), processorMenu(), promptProcessor(), startMenu(), and UI().
printMetadata()
void UI::printMetadata (const FileManager & file)
Definition at line 39 of file UI.cpp.
{
     clearConsole();
     println("METADATA");
     std::cout << "File Name:       " << file.getFileName() << "\n";
     std::cout << "Audio Format:    " << file.getAudioFormat() << "\n";
     std::cout << "Mono/Stereo:     " << file.getMonoStereo() << "\n";
     std::cout << "Sample Rate:     " << file.getSampleRate() << "\n";
     std::cout << "Byte Rate:       " << file.getByteRate() << "\n";
     std::cout << "Bitdepth:        " << file.getBitsPerSample() << "\n";
     std::cout << "Block Align:     " << file.getBlockAlign() << "\n";
     delay(3);
 }
References clearConsole(), delay(), FileManager::getAudioFormat(), FileManager::getBitsPerSample(), FileManager::getBlockAlign(), FileManager::getByteRate(), FileManager::getFileName(), FileManager::getMonoStereo(), FileManager::getSampleRate(), and println().
Referenced by main().
processorMenu()
std::string UI::processorMenu ()
Definition at line 52 of file UI.cpp.
{
     std::cout << "\n";
     println("Please select a processor or press \"0\" to exit:");
     println("(0) EXIT");
     println("(1) Normalization");
     println("(2) Echo");
     println("(3) Gain Adjustment");
     std::string userInput;
     std::cin >> userInput;
     return userInput;
 }
References println().
Referenced by main().
promptGain()
int UI::promptGain (const std::string &) private
promptProcessor()
int UI::promptProcessor (const std::string & prompt, const std::string & shortPrompt) private
Definition at line 102 of file UI.cpp.
{
     println(prompt);
     std::string userInput;
     bool isValid = false;
     do {
         std::cout << shortPrompt;
         std::cin >> userInput;
         if (!userInput.empty() && userInput.find_first_not_of("0123456789") == std::string::npos && userInput.length() < 6) {
             isValid = true;
         } else {
             printError();
         }
     } while (!isValid);
     return (std::stoi(userInput));
 }
References printError(), and println().
Referenced by echoOptions(), and gainOption().
startMenu()
std::string UI::startMenu ()
Definition at line 9 of file UI.cpp.
{
     println("Do you wish to continue (Y/n)");
     std::string userInput;
     std::cin >> userInput;
     return userInput;
 }
References println().
Referenced by main().
The documentation for this class was generated from the following files:
UI.h
UI.cpp