Doxygen: FileManager Class Reference
FileManager Class Reference
#include <FileManager.h>
Public Member Functions
virtual ~FileManager ()
void checkHeader (const std::string &)
bool writeFile (std::string)
std::string getFileName () const
std::string getAudioFormat () const
std::string getMonoStereo () const
int getSampleRate () const
int getByteRate () const
short getBlockAlign () const
short getBitsPerSample () const
double getFileDuration () const
const std::vector< float > & getSamples () const
Public Attributes
char * data
Private Member Functions
void readHeader (std::ifstream &)
void readData (std::ifstream &)
void convertRawData ()
float convertToFloat (unsigned char)
float convertToFloat (short)
unsigned char convertTo8B (float)
short convertTo16B (float)
Private Attributes
WAV_HEADER header
std::string fileName
std::vector< float > samples
Detailed Description
Definition at line 11 of file FileManager.h.
Constructor & Destructor Documentation
~FileManager()
FileManager::~FileManager () virtual
Definition at line 6 of file FileManager.cpp.
{
     delete[] data;
 }
References data.
Member Function Documentation
checkHeader()
void FileManager::checkHeader (const std::string & inFile)
Definition at line 10 of file FileManager.cpp.
{
     /*
     std::cout << header.riff_header[4] << "\n";
     std::cout << header.wav_size << "\n";
     std::cout << header.wave_header << "\n";
     std::cout << header.fmt_header << "\n";
     std::cout << header.fmt_chunk_size << "\n";
     std::cout << header.audio_format << "\n";
     std::cout << header.num_channels << "\n";
     std::cout << header.sample_rate << "\n";
     std::cout << header.data_header << "\n";
     */
     std::ifstream ifs;
     ifs.open(inFile, std::ios::binary | std::ios::in);
     if (ifs.is_open()) {
         fileName = inFile;
         readHeader(ifs);
         if (strncmp(header.riff_header, "RIFF", 4) == 0) {
             if(strncmp(header.wave_header, "WAVE", 4) == 0) {
                 if (strncmp(header.fmt_header, "fmt ", 4) == 0) {
                     //readData(ifs);
                     //convertRawData();
                 } else {
                     throw std::runtime_error("File does not have proper format.");
                 }
             } else {
                 throw std::runtime_error("RIFF file is not a WAVE file.");
             }
         } else {
             throw std::runtime_error("File is not a RIFF file.");
         }
         ifs.close();
     } else {
         throw std::runtime_error("File could not be opened.");
     }
 }
References fileName, WAV_HEADER::fmt_header, header, readHeader(), WAV_HEADER::riff_header, and WAV_HEADER::wave_header.
Referenced by main().
convertRawData()
void FileManager::convertRawData () private
Definition at line 91 of file FileManager.cpp.
{
     if(header.bit_depth == 8) {
         for(size_t i = 0; i < header.data_bytes; i++) {
             samples.push_back(convertToFloat(*(reinterpret_cast<unsigned char*>(&data[i]))));
         }
     } else if (header.bit_depth == 16) {
         for(size_t i = 0; i < header.data_bytes; i += 2) {
             short shortSample = 0;
             *(reinterpret_cast<char*>(&shortSample)) = data[i];
             *(reinterpret_cast<char*>(&shortSample) + 1) = data[i + 1];
             samples.push_back(convertToFloat(shortSample));
         }
     } else {
         std::cout << "ERROR: convertRawData() bit depth\n\n";
     }
     // Check samples
     // for (int i = 0; i < 20; i++) {
     //     std::cout << samples[i] << " ";
     // }
 }
References WAV_HEADER::bit_depth, convertToFloat(), data, WAV_HEADER::data_bytes, header, and samples.
convertTo16B()
short FileManager::convertTo16B (float sample) private
Definition at line 152 of file FileManager.cpp.
{
     return sample / (1.0f / 32768.0f);
 }
Referenced by writeFile().
convertTo8B()
unsigned char FileManager::convertTo8B (float sample) private
Definition at line 149 of file FileManager.cpp.
{
     return (sample + 1.0f) / (2.0f / 255.0f);
 }
Referenced by writeFile().
convertToFloat() [1/2]
float FileManager::convertToFloat (short data) private
Definition at line 145 of file FileManager.cpp.
{
     return 0.0f + (1.0f / 32768.0f) * static_cast<float>(data);
 }
References data.
convertToFloat() [2/2]
float FileManager::convertToFloat (unsigned char data) private
Definition at line 142 of file FileManager.cpp.
{
     return -1.0f + (2.0f / 255.0f) * static_cast<float>(*(reinterpret_cast<unsigned char*>(&data)));
 }
References data.
Referenced by convertRawData().
getAudioFormat()
std::string FileManager::getAudioFormat () const
Definition at line 112 of file FileManager.cpp.
{
     std::string audioFormat;
     switch (header.audio_format) {
     case 0:
         audioFormat = "Unknown";
         break;
     case 1:
         audioFormat = "1 (PCM)";
         break;
     case 3:
         audioFormat = "3 (IEEE Floating-Point)";
         break;
     default:
         audioFormat = "Other Compressed fmt";
         break;
     }
     return audioFormat;
 }
References WAV_HEADER::audio_format, and header.
Referenced by UI::printMetadata().
getBitsPerSample()
short FileManager::getBitsPerSample () const inline
Definition at line 38 of file FileManager.h.
 { return header.bit_depth; }
References WAV_HEADER::bit_depth, and header.
Referenced by UI::printMetadata().
getBlockAlign()
short FileManager::getBlockAlign () const inline
Definition at line 37 of file FileManager.h.
 { return header.sample_alignment; }
References header, and WAV_HEADER::sample_alignment.
Referenced by UI::printMetadata().
getByteRate()
int FileManager::getByteRate () const inline
Definition at line 34 of file FileManager.h.
 { return header.byte_rate; }
References WAV_HEADER::byte_rate, and header.
Referenced by UI::printMetadata().
getFileDuration()
double FileManager::getFileDuration () const
Definition at line 138 of file FileManager.cpp.
{
     return (double)header.data_bytes / (((double)header.sample_rate) * ((double)header.num_channels) * ((double)header.bit_depth) / 8);
 }
References WAV_HEADER::bit_depth, WAV_HEADER::data_bytes, header, WAV_HEADER::num_channels, and WAV_HEADER::sample_rate.
Referenced by UI::echoOptions().
getFileName()
std::string FileManager::getFileName () const inline
Definition at line 30 of file FileManager.h.
 { return fileName; }
References fileName.
Referenced by UI::printMetadata().
getMonoStereo()
std::string FileManager::getMonoStereo () const
Definition at line 131 of file FileManager.cpp.
{
     std::string numChannels = "Not Mono/Stereo";
     if (header.num_channels == 1) { numChannels = "Mono"; }
     else if (header.num_channels == 2) { numChannels = "Stereo"; }
     return numChannels;
 }
References header, and WAV_HEADER::num_channels.
Referenced by UI::printMetadata().
getSampleRate()
int FileManager::getSampleRate () const inline
Definition at line 33 of file FileManager.h.
 { return header.sample_rate; }
References header, and WAV_HEADER::sample_rate.
Referenced by UI::printMetadata().
getSamples()
const std::vector<float>& FileManager::getSamples () const inline
Definition at line 40 of file FileManager.h.
 { return samples; }
References samples.
readData()
void FileManager::readData (std::ifstream & ifs) private
Definition at line 56 of file FileManager.cpp.
{
     data = new char[header.data_bytes];
     ifs.read((char*)data, header.data_bytes);
 }
References data, WAV_HEADER::data_bytes, and header.
readHeader()
void FileManager::readHeader (std::ifstream & ifs) private
Definition at line 47 of file FileManager.cpp.
{
     ifs.read((char*) &header, sizeof(header));
     // ifs.read((char*) &header.riff_header, sizeof(header.riff_header));
     // ifs.read((char*) &header.wav_size, sizeof(header.wav_size));
     // ifs.read((char*) &header.wave_header, sizeof(header.wave_header));
     // ifs.read((char*) &header.fmt_header, sizeof(header.fmt_header));
     // ifs.read((char*) &header, sizeof(header) - 16);
 }
References header.
Referenced by checkHeader().
writeFile()
bool FileManager::writeFile (std::string newFileName)
Definition at line 61 of file FileManager.cpp.
{
     std::ofstream file(newFileName, std::ios::binary);
     bool fileWritten = true;
     if (file.is_open()) {
         file.write((char*) &header, sizeof(header));
         if (header.bit_depth == 8) {
             for (size_t i = 0; i < header.data_bytes; i++) {
                 data[i] = convertTo8B(samples[i]);
             }
         } else if (header.bit_depth == 16) {
             int num = 0;
             for(size_t i = 0; i < header.data_bytes; i += 2) {
                 short temp = convertTo16B(samples[num]);
                 unsigned char lsb = *(reinterpret_cast<unsigned char*>(&temp));
                 unsigned char msb = *(reinterpret_cast<unsigned char*>(&temp) + 1);
                 data[i] = lsb;
                 data[i + 1] = msb;
                 num++;
             }
         } else {
             fileWritten = false;
         }
         file.write(data, header.data_bytes);
         file.close();
     } else {
         fileWritten = false;
     }
     return fileWritten;
 }
References WAV_HEADER::bit_depth, convertTo16B(), convertTo8B(), data, WAV_HEADER::data_bytes, header, and samples.
Member Data Documentation
data
char* FileManager::data
Definition at line 24 of file FileManager.h.
Referenced by convertRawData(), convertToFloat(), readData(), writeFile(), and ~FileManager().
fileName
std::string FileManager::fileName private
Definition at line 13 of file FileManager.h.
Referenced by checkHeader(), and getFileName().
header
WAV_HEADER FileManager::header private
Definition at line 12 of file FileManager.h.
Referenced by checkHeader(), convertRawData(), getAudioFormat(), getBitsPerSample(), getBlockAlign(), getByteRate(), getFileDuration(), getMonoStereo(), getSampleRate(), readData(), readHeader(), and writeFile().
samples
std::vector<float> FileManager::samples private
Definition at line 14 of file FileManager.h.
Referenced by convertRawData(), getSamples(), and writeFile().
The documentation for this class was generated from the following files:
FileManager.h
FileManager.cpp